<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-8M27IT2" failures="3" tests="7" name=" RegisterTest" time="68.939" errors="0" timestamp="2023-05-22T18:53:17 EDT">
  <testcase classname="tutorialsNinja.RegisterTest" name="registerWithCredentials" time="2.785"/>
  <testcase classname="tutorialsNinja.RegisterTest" name="registerWithCredentials" time="2.588">
    <failure type="java.lang.AssertionError" message="Registration success mismatch for credentials: firstName=invalidFirstName, lastName=inavalidlastname, email=sun@, phoneNumber=abcd, password=sun, confirmPassword=sun expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Registration success mismatch for credentials: firstName=invalidFirstName, lastName=inavalidlastname, email=sun@, phoneNumber=abcd, password=sun, confirmPassword=sun expected [true] but found [false]
at tutorialsNinja.RegisterTest.registerWithCredentials(RegisterTest.java:71)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- registerWithCredentials -->
  <testcase classname="tutorialsNinja.RegisterTest" name="registerWithCredentials" time="3.035"/>
  <testcase classname="tutorialsNinja.RegisterTest" name="registerWithInvalidPhoneNumber" time="2.541">
    <failure type="java.lang.AssertionError" message="The user is able to register with an invalid phone number expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: The user is able to register with an invalid phone number expected [false] but found [true]
at tutorialsNinja.RegisterTest.registerWithInvalidPhoneNumber(RegisterTest.java:108)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- registerWithInvalidPhoneNumber -->
  <testcase classname="tutorialsNinja.RegisterTest" name="verifyRegisterWithAnExistingEmailAddress" time="3.1"/>
  <testcase classname="tutorialsNinja.RegisterTest" name="VerifyThePasswordNotVisibleToTheSourcePage" time="1.62">
    <failure type="java.lang.AssertionError" message="the password is visible expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: the password is visible expected [true] but found [false]
at tutorialsNinja.RegisterTest.VerifyThePasswordNotVisibleToTheSourcePage(RegisterTest.java:139)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- VerifyThePasswordNotVisibleToTheSourcePage -->
  <testcase classname="tutorialsNinja.RegisterTest" name="VerifyDifferentWaysToNavigateToTheRegisterPage" time="4.151"/>
</testsuite> <!--  RegisterTest -->
