<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-8M27IT2" failures="3" tests="9" name=" RegisterTest" time="154.918" errors="0" timestamp="2023-05-29T00:37:24 EDT">
  <testcase classname="tutorialsNinja.RegisterTest" name="vrfyUsrNvgtRgstrHmPge" time="1.523"/>
  <testcase classname="tutorialsNinja.RegisterTest" name="registerWithCredentials" time="3.006"/>
  <testcase classname="tutorialsNinja.RegisterTest" name="registerWithCredentials" time="2.482"/>
  <testcase classname="tutorialsNinja.RegisterTest" name="registerWithInvalidPhoneNumber" time="2.45">
    <failure type="java.lang.AssertionError" message="The user is able to register with an invalid phone number expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: The user is able to register with an invalid phone number expected [false] but found [true]
at tutorialsNinja.RegisterTest.registerWithInvalidPhoneNumber(RegisterTest.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- registerWithInvalidPhoneNumber -->
  <testcase classname="tutorialsNinja.RegisterTest" name="verifyRegisterWithAnExistingEmailAddress" time="3.246"/>
  <testcase classname="tutorialsNinja.RegisterTest" name="VerifyThePasswordNotVisibleToTheSourcePage" time="2.067">
    <failure type="java.lang.AssertionError" message="the password is visible expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: the password is visible expected [true] but found [false]
at tutorialsNinja.RegisterTest.VerifyThePasswordNotVisibleToTheSourcePage(RegisterTest.java:164)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- VerifyThePasswordNotVisibleToTheSourcePage -->
  <testcase classname="tutorialsNinja.RegisterTest" name="VerifyDifferentWaysToNavigateToTheRegisterPage" time="3.269"/>
  <testcase classname="tutorialsNinja.RegisterTest" name="checkPrivacyPolicyCheckBox" time="2.997"/>
  <testcase classname="tutorialsNinja.RegisterTest" name="checkPrivacyPolicyCheckBox" time="2.752">
    <failure type="java.lang.AssertionError" message="The user should not be able to register when the privacy policy checkbox is not selected expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: The user should not be able to register when the privacy policy checkbox is not selected expected [false] but found [true]
at tutorialsNinja.RegisterTest.checkPrivacyPolicyCheckBox(RegisterTest.java:248)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- checkPrivacyPolicyCheckBox -->
</testsuite> <!--  RegisterTest -->
